### ISSUE TITLE
TODO - Sprint 2 ( 5th March -19thMarch)

### ISSUE THREAD

**Issue by dpalleti** [UMass-Rescue/IntelligentInformationExtractor#2]
- [ ] Decided on the user interface flow.
- [ ] Implemented the Login/sign-up flow.
- [ ] Implemented just the front-end page of the file upload
- [ ] Dashboard view of the user with history .

**Comment by saivineethkumar** [comment]
- [ ] Familiarize with Flask framework
- [ ] Decide on database
- [ ] Create models for the data storage.
- [ ] Implement backend code for login/signup

**Comment by ahrthisuresh** [comment]
- [ ] Design and implement a new database schema tailored for storing stories of child abuse, psychology of child abuse, prevention methods, and helpline numbers.
- [ ] Research and select appropriate  models for scraping and analyzing data from the database.
- [ ] Fine-tune models and parameters to optimize efficiency and accuracy.

**Comment by fcmcgowan** [comment]
- [ ] Continue to test models/open-source libraries to select best fit for project
- [ ] Find text sample more related to goals of application (use by law enforcement) to test models
- [ ] Select library to use (and begin to finalize models)
