### ISSUE TITLE
TODO - (2nd April - 16th April)

### ISSUE THREAD

**Issue by dpalleti** [UMass-Rescue/IntelligentInformationExtractor#4]
- [ ] Login/Signup/Log out pages integration with backend
- [ ] No direct access to the Dashboard page
- [x] Navigation bar - backend integration
- [ ] Profile backend integration
- [x] Activity/back end integration

**Comment by ahrthisuresh** [comment]
- [ ] Increase model efficiency.
- [ ] Research on how to integrate to the existing front end.
- [ ] Run the model with larger dataset and better datasets.
- [ ] Write Prompts suitable for the datasets in order to extract the required information.

**Comment by saivineethkumar** [comment]
- [ ] Integrating login, signup pages with the frontend
- [ ] Integrating Dashboard and Activity pages with frontend
- [ ] Integrating ML module with the backend (from last time)
- [ ] Research on how to scale the application
- [ ] Research on Fileserver setup
