### ISSUE TITLE
TODO 16th April - 30th April

### ISSUE THREAD

**Issue by dpalleti** [UMass-Rescue/IntelligentInformationExtractor#5]

**Comment by fcmcgowan** [comment]
- [ ] Resolve access key error/move on with alternative
- [ ] Test data with prompts 
- [ ] Record results for each task and data
- [ ] Modify prompts as needed/ finalize

**Comment by ahrthisuresh** [comment]
- [x] Work on building efficient model
- [x] Fix the bugs such as token error 
- [x] Extracting more relevant information
- [x] Integrating ML part to the backend
